### ISSUE TITLE
Error Making Directory after First Run

### ISSUE THREAD

**Issue by Creodahn** [Creodahn/markdown-wiki-initializer#1]
On Windows, the script throws an error on trying to create the containing folder after the first run.

**Expected behavior**: runs successfully, adding Markdown files and directories for newly added source code

**Actual behavior**:

```
return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir 'c:\tmp\wiki\components'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at makeDirectory (C:\Projects\markdown-wiki-initializer\index.js:49:8)
    at handleDirectory (C:\Projects\markdown-wiki-initializer\index.js:41:3)
    at Object.<anonymous> (C:\Projects\markdown-wiki-initializer\index.js:13:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)```

**Comment by Creodahn** [comment]
Fixed by https://github.com/Creodahn/markdown-wiki-initializer/commit/692f35e28802df5744aad435edb11d5f0a26cfe4
